package manage_comference.entity;
// Generated Jul 30, 2020 2:27:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Diadiem generated by hbm2java
 */
public class Diadiem  implements java.io.Serializable {


     private Integer idDd;
     private String tenDd;
     private String diachi;
     private Integer succhua;
     private Set hoinghis = new HashSet(0);

    public Diadiem() {
    }

    public Diadiem(String tenDd, String diachi, Integer succhua, Set hoinghis) {
       this.tenDd = tenDd;
       this.diachi = diachi;
       this.succhua = succhua;
       this.hoinghis = hoinghis;
    }
   
    public Integer getIdDd() {
        return this.idDd;
    }
    
    public void setIdDd(Integer idDd) {
        this.idDd = idDd;
    }
    public String getTenDd() {
        return this.tenDd;
    }
    
    public void setTenDd(String tenDd) {
        this.tenDd = tenDd;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Integer getSucchua() {
        return this.succhua;
    }
    
    public void setSucchua(Integer succhua) {
        this.succhua = succhua;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }




}


