package manage_comference.entity;
// Generated Jul 30, 2020 2:27:59 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoinghi generated by hbm2java
 */
public class Hoinghi  implements java.io.Serializable {


     private Integer idHn;
     private Diadiem diadiem;
     private String tenHn;
     private String mota;
     private String motaChitiet;
     private String hinhanh;
     private Date thoigian;
     private Set participantsSignups = new HashSet(0);
     private Set participantses = new HashSet(0);

    public Hoinghi() {
    }

    public Hoinghi(Diadiem diadiem, String tenHn, String mota, String motaChitiet, String hinhanh, Date thoigian, Set participantsSignups, Set participantses) {
       this.diadiem = diadiem;
       this.tenHn = tenHn;
       this.mota = mota;
       this.motaChitiet = motaChitiet;
       this.hinhanh = hinhanh;
       this.thoigian = thoigian;
       this.participantsSignups = participantsSignups;
       this.participantses = participantses;
    }
   
    public Integer getIdHn() {
        return this.idHn;
    }
    
    public void setIdHn(Integer idHn) {
        this.idHn = idHn;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public String getTenHn() {
        return this.tenHn;
    }
    
    public void setTenHn(String tenHn) {
        this.tenHn = tenHn;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public String getMotaChitiet() {
        return this.motaChitiet;
    }
    
    public void setMotaChitiet(String motaChitiet) {
        this.motaChitiet = motaChitiet;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    public Date getThoigian() {
        return this.thoigian;
    }
    
    public void setThoigian(Date thoigian) {
        this.thoigian = thoigian;
    }
    public Set getParticipantsSignups() {
        return this.participantsSignups;
    }
    
    public void setParticipantsSignups(Set participantsSignups) {
        this.participantsSignups = participantsSignups;
    }
    public Set getParticipantses() {
        return this.participantses;
    }
    
    public void setParticipantses(Set participantses) {
        this.participantses = participantses;
    }




}


