package manage_comference.entity;
// Generated Jul 30, 2020 2:27:59 PM by Hibernate Tools 4.3.1



/**
 * Participants generated by hbm2java
 */
public class Participants  implements java.io.Serializable {


     private Integer id;
     private AdUser adUser;
     private Hoinghi hoinghi;

    public Participants() {
    }

    public Participants(AdUser adUser, Hoinghi hoinghi) {
       this.adUser = adUser;
       this.hoinghi = hoinghi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public AdUser getAdUser() {
        return this.adUser;
    }
    
    public void setAdUser(AdUser adUser) {
        this.adUser = adUser;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }




}


